#!/bin/sh
set -e

if [ ! -e virtualenv/ok ]; then
    python -m virtualenv virtualenv
    ./virtualenv/bin/pip install zbase32
    touch virtualenv/ok
fi

source $PWD/virtualenv/bin/activate

go test -test.run=Python "$@"
